### ISSUE TITLE
Video bandwidth values are high

### ISSUE THREAD

**Issue by JensenPaul** [GrumpyOldTroll/wicg-multicast-receiver-api#2]
These values seem high:
40 mbps: bit-rate for 4k video
10 mbps: bit-rate for 1080p video

Netflix published rates from https://help.netflix.com/en/node/87 are:
"up to" 15.6 mbps for 4k video
"up to" 6.7 mbps for 1080p video

Xfinity estimates https://dataplan.xfinity.com/estimator/
17.8 mbps for 4k video
3.8 mbps for 1080p video

YouTube rates https://support.google.com/youtube/answer/78358
20 mbps for 4k video
5 mbps for 1080p video

**Comment by GrumpyOldTroll** [comment]
Sorry for the slow response, I somehow didn't see the notice on this.

I was working from this link:
https://support.google.com/youtube/answer/1722171?hl=en

In the Bitrate section, it gives 35-45 Mbps as the recommended bitrate for 4k (at 30fps).

It looks like this difference seems to be upload vs. download?  I'm not completely sure where this discrepancy comes from, but the point is well-taken, we should adjust the numbers to a better downloading estimate, thanks.

**Comment by JensenPaul** [comment]
I'd guess upload rates are higher to ensure the "golden copy" can be down-sampled as accurately as possible.  Perhaps providing a higher quality original also provides more proof of content ownership.

**Comment by GrumpyOldTroll** [comment]
I believe the latest updates have addressed this, so I'm closing the issue now with thanks for raising it.
